/**
 * Test profiles mapped to field `name` attributes used in this app.
 * Keys match exactly what React Hook Form sees — the `name` prop on each field component.
 *
 * Field name reference:
 *   Text:     firstName, lastName, email, address, addressApt, city, zipCode
 *   Select:   state, citizenshipStatus, employmentStatus, residentialStatus (tab), contactPreference (tab), purchaseIntent (tab)
 *   Date:     birthDate (MM/DD/YYYY), residentialDate (MM/YYYY), employerDate (MM/YYYY)
 *   Masked:   phoneNumber, ssn, employerPhone
 *   Currency: yearlyIncome, monthlyHousePayment
 *   Tab:      residentialStatus, contactPreference, purchaseIntent, condition
 *
 * Co-applicant fields use the same keys prefixed with "coapplicant_" in the source data,
 * but in CoApplicant.tsx the field names are unprefixed (firstName, lastName, etc.)
 * so we store them separately under `coApplicant`.
 */

const PROFILES = {
  george_beer_approved: {
    label: "George Beer — Approved",
    primary: {
      firstName: "GEORGE",
      lastName: "BEER",
      birthDate: "09/15/1941",
      address: "116 State St",
      addressApt: "85",
      city: "Holmen",
      state: "NV",
      zipCode: "54636",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 170000,
      contactPreference: "call",
      phoneNumber: "6085261867",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666570450",
    },
  },

  tanya_perrine_approved: {
    label: "Tanya Perrine — Approved",
    primary: {
      firstName: "TANYA",
      lastName: "PERRINE",
      birthDate: "09/26/1952",
      address: "789 POWERS RD",
      city: "CONKLIN",
      state: "NY",
      zipCode: "13748",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 48000,
      contactPreference: "call",
      phoneNumber: "6077249711",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666290559",
    },
  },

  tanya_perrine_declined: {
    label: "Tanya Perrine — Declined (dealer review)",
    primary: {
      firstName: "TANYA",
      lastName: "PERRINE",
      birthDate: "09/26/1952",
      address: "789 POWERS RD",
      city: "CONKLIN",
      state: "NY",
      zipCode: "13748",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 16000,
      contactPreference: "call",
      phoneNumber: "6077249711",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666290559",
    },
  },

  cathy_bellamy_declined: {
    label: "Cathy Bellamy — Full Decline",
    primary: {
      firstName: "CATHY",
      lastName: "BELLAMY",
      birthDate: "08/26/1966",
      address: "315 HUDSON AVE",
      city: "STILLWATER",
      state: "NY",
      zipCode: "12170",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 48000,
      contactPreference: "call",
      phoneNumber: "5186643027",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666275271",
    },
  },

  donald_madera_thinfile: {
    label: "Donald Madera — Thinfile 9001",
    primary: {
      firstName: "DONALD",
      lastName: "MADERA",
      birthDate: "12/06/1916",
      address: "4212 ALABAMA AVE",
      city: "KENNER",
      state: "LA",
      zipCode: "70065",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 48000,
      contactPreference: "call",
      phoneNumber: "5044662001",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 4000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666523068",
    },
  },

  jeanette_robinson_locked: {
    label: "Jeanette Robinson — Credit Locked",
    primary: {
      firstName: "Jeanette",
      lastName: "Robinson",
      birthDate: "11/10/1972",
      address: "2593 Vonoa Drive",
      city: "Radcliff",
      state: "KY",
      zipCode: "40160",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 120000,
      contactPreference: "call",
      phoneNumber: "2297347497",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 9000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666114114",
    },
  },

  george_tanya_joint: {
    label: "George Beer + Tanya Perrine — Joint Approved",
    primary: {
      firstName: "GEORGE",
      lastName: "BEER",
      birthDate: "09/15/1941",
      address: "116 State St",
      addressApt: "85",
      city: "Holmen",
      state: "NV",
      zipCode: "54636",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 120000,
      contactPreference: "call",
      phoneNumber: "6085261867",
      purchaseIntent: "week",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666570450",
    },
    coApplicant: {
      relationshipToPrimary: "SPOUSE",
      firstName: "TANYA",
      lastName: "PERRINE",
      birthDate: "09/26/1952",
      reusePrimaryAddress: "NO",
      address: "789 POWERS RD",
      city: "CONKLIN",
      state: "NY",
      zipCode: "13748",
      residentialStatus: "R",
      residentialDate: "01/2020",
      employmentStatus: "employed",
      yearlyIncome: 48000,
      phoneNumber: "6077249711",
      citizenshipStatus: "us_citizen",
      monthlyHousePayment: 1000,
      employerName: "Octane",
      employerPhone: "5165165165",
      jobTitle: "Bug Hunter",
      employerDate: "01/2020",
      ssn: "666290559",
    },
  },
};
